import Head from "next/head";
import Image from "next/image";
import About from "../components/About/About";
import Contact from "../components/Contact/Contact";
import Main from "../components/Main/Main";
import Navbar from "../components/Navbar/Navbar";
import Project from "../components/Projects/Projects";
import Skills from "../components/Skills/Skills";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sangam | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <About />
      <Skills />
      <Project />
      <Contact />
    </div>
  );
}
